import { type NextRequest } from 'next/server'
import { getLiveGames } from '../../data/games'
import { getAllPosts } from '../../lib/blog'
import { getAllProjects } from '../../lib/projects'

const BASE_URL = 'https://yorayriniwnl.vercel.app'

export const runtime = 'nodejs'

type SitemapRoute = {
  path: string
  priority: string
  changefreq: string
  lastmod?: string
}

const STATIC_ROUTES: SitemapRoute[] = [
  { path: '/',                priority: '1.0', changefreq: 'weekly'  },
  { path: '/projects',        priority: '0.9', changefreq: 'weekly'  },
  { path: '/resume',          priority: '0.9', changefreq: 'monthly' },
  { path: '/cv',              priority: '0.8', changefreq: 'monthly' },
  { path: '/about',           priority: '0.8', changefreq: 'monthly' },
  { path: '/blog',            priority: '0.8', changefreq: 'weekly'  },
  { path: '/dashboard',       priority: '0.8', changefreq: 'weekly'  },
  { path: '/profile',         priority: '0.8', changefreq: 'monthly' },
  { path: '/skills',          priority: '0.7', changefreq: 'monthly' },
  { path: '/contact',         priority: '0.7', changefreq: 'monthly' },
  { path: '/experience',      priority: '0.7', changefreq: 'monthly' },
  { path: '/timeline',        priority: '0.7', changefreq: 'monthly' },
  { path: '/achievements',    priority: '0.7', changefreq: 'monthly' },
  { path: '/onboarding',      priority: '0.6', changefreq: 'monthly' },
  { path: '/hobbies',         priority: '0.6', changefreq: 'monthly' },
  { path: '/devlog',          priority: '0.6', changefreq: 'weekly'  },
  { path: '/stats',           priority: '0.6', changefreq: 'weekly'  },
  { path: '/value-education', priority: '0.6', changefreq: 'monthly' },
  { path: '/gallery',         priority: '0.5', changefreq: 'monthly' },
  { path: '/media',           priority: '0.5', changefreq: 'monthly' },
  { path: '/games',           priority: '0.5', changefreq: 'monthly' },
  { path: '/steam',           priority: '0.5', changefreq: 'monthly' },
  { path: '/search',          priority: '0.5', changefreq: 'monthly' },
  { path: '/settings',        priority: '0.4', changefreq: 'monthly' },
  { path: '/fun',             priority: '0.4', changefreq: 'monthly' },
  { path: '/avatar',          priority: '0.3', changefreq: 'monthly' },
  { path: '/three-demo',      priority: '0.3', changefreq: 'monthly' },
]

function buildUrlEntry(
  loc: string,
  changefreq: string,
  priority: string,
  lastmod: string,
): string {
  return [
    '  <url>',
    `    <loc>${loc}</loc>`,
    `    <lastmod>${lastmod}</lastmod>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ].join('\n')
}

function toDateOnly(value?: string): string | undefined {
  if (!value) return undefined

  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return undefined

  return date.toISOString().split('T')[0]
}

function toProjectPriority(featured?: boolean, autoGenerated?: boolean): string {
  if (featured) return '0.85'
  if (autoGenerated) return '0.55'
  return '0.75'
}

function buildEntries(routes: SitemapRoute[], fallbackLastmod: string): string[] {
  const seen = new Set<string>()

  return routes.flatMap(({ path, priority, changefreq, lastmod }) => {
    const loc = `${BASE_URL}${path}`
    if (seen.has(loc)) return []

    seen.add(loc)
    return buildUrlEntry(loc, changefreq, priority, lastmod ?? fallbackLastmod)
  })
}

export function GET(_req: NextRequest): Response {
  const lastmod = new Date().toISOString().split('T')[0]

  const projectRoutes = getAllProjects().map((project): SitemapRoute => ({
    path: `/projects/${encodeURIComponent(project.id)}`,
    changefreq: 'monthly',
    priority: toProjectPriority(project.featured, project.autoGenerated),
    lastmod: toDateOnly(project.lastUpdated ?? project.date),
  }))

  const blogRoutes = getAllPosts().map((post): SitemapRoute => ({
    path: `/blog/${encodeURIComponent(post.slug)}`,
    changefreq: 'monthly',
    priority: post.featured ? '0.75' : '0.65',
    lastmod: toDateOnly(post.date),
  }))

  const gameRoutes = getLiveGames().map((game): SitemapRoute => ({
    path: `/games/${encodeURIComponent(game.slug)}`,
    changefreq: 'monthly',
    priority: game.featured ? '0.65' : '0.55',
  }))

  const entries = buildEntries(
    [...STATIC_ROUTES, ...projectRoutes, ...blogRoutes, ...gameRoutes],
    lastmod,
  )

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...entries,
    '</urlset>',
  ].join('\n')

  return new Response(xml, {
    status: 200,
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=86400, stale-while-revalidate=3600',
    },
  })
}
