import { type NextRequest } from 'next/server'
import { PROJECTS } from '../../data/projects'

const BASE_URL = 'https://yorayriniwnl.vercel.app'

const STATIC_ROUTES: { path: string; priority: string; changefreq: string }[] = [
  { path: '/',                priority: '1.0', changefreq: 'weekly'  },
  { path: '/projects',        priority: '0.9', changefreq: 'weekly'  },
  { path: '/resume',          priority: '0.9', changefreq: 'monthly' },
  { path: '/cv',              priority: '0.8', changefreq: 'monthly' },
  { path: '/about',           priority: '0.8', changefreq: 'monthly' },
  { path: '/dashboard',       priority: '0.8', changefreq: 'weekly'  },
  { path: '/skills',          priority: '0.7', changefreq: 'monthly' },
  { path: '/contact',         priority: '0.7', changefreq: 'monthly' },
  { path: '/experience',      priority: '0.7', changefreq: 'monthly' },
  { path: '/timeline',        priority: '0.7', changefreq: 'monthly' },
  { path: '/achievements',    priority: '0.7', changefreq: 'monthly' },
  { path: '/hobbies',         priority: '0.6', changefreq: 'monthly' },
  { path: '/devlog',          priority: '0.6', changefreq: 'weekly'  },
  { path: '/stats',           priority: '0.6', changefreq: 'weekly'  },
  { path: '/value-education', priority: '0.6', changefreq: 'monthly' },
  { path: '/gallery',         priority: '0.5', changefreq: 'monthly' },
  { path: '/media',           priority: '0.5', changefreq: 'monthly' },
  { path: '/games',           priority: '0.5', changefreq: 'monthly' },
  { path: '/steam',           priority: '0.5', changefreq: 'monthly' },
  { path: '/search',          priority: '0.5', changefreq: 'monthly' },
  { path: '/settings',        priority: '0.4', changefreq: 'monthly' },
  { path: '/fun',             priority: '0.4', changefreq: 'monthly' },
]

function buildUrlEntry(
  loc: string,
  changefreq: string,
  priority: string,
  lastmod: string,
): string {
  return [
    '  <url>',
    `    <loc>${loc}</loc>`,
    `    <lastmod>${lastmod}</lastmod>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ].join('\n')
}

export function GET(_req: NextRequest): Response {
  const lastmod = new Date().toISOString().split('T')[0]

  const staticEntries = STATIC_ROUTES.map(({ path, priority, changefreq }) =>
    buildUrlEntry(`${BASE_URL}${path}`, changefreq, priority, lastmod),
  )

  // Derive project slugs from the live PROJECTS array — no hardcoded list
  const projectEntries = PROJECTS.filter((p) => !p.autoGenerated).map((p) =>
    buildUrlEntry(
      `${BASE_URL}/projects/${p.id}`,
      'monthly',
      p.featured ? '0.85' : '0.75',
      p.lastUpdated ? p.lastUpdated.split('T')[0] : lastmod,
    ),
  )

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...staticEntries,
    ...projectEntries,
    '</urlset>',
  ].join('\n')

  return new Response(xml, {
    status: 200,
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=86400, stale-while-revalidate=3600',
    },
  })
}
