'use client'

import React, { useMemo, useState } from 'react'
import Link from 'next/link'
import type { Project } from '../../data/site'
import Badge from '../ui/Badge'
import Card from '../ui/Card'
import Container from '../ui/Container'
import Divider from '../ui/Divider'
import Tabs from '../ui/Tabs'
import Text from '../ui/Text'
import { ButtonLink } from '../ui/Button'
import { Heading, Subheading } from '../ui/Typography'

type ProjectCollectionProps = {
  description?: string
  projects: Project[]
  title: string
}

const STAGE_ORDER = ['released', 'evolving', 'coming-up'] as const

const STAGE_META: Record<(typeof STAGE_ORDER)[number], { title: string; description: string }> = {
  released: {
    title: 'Released',
    description: 'Production-ready projects with clear outcomes and public proof.',
  },
  evolving: {
    title: 'Evolving',
    description: 'Active builds with strong momentum and ongoing iteration.',
  },
  'coming-up': {
    title: 'Coming Up',
    description: 'Planned initiatives in development with directional signal.',
  },
}

const MOMENTUM_META: Record<
  NonNullable<Project['momentum']>,
  { label: string; variant?: React.ComponentProps<typeof Badge>['variant'] }
> = {
  featured: { label: 'Featured 100%', variant: 'gold' },
  advancing: { label: 'Advancing 70%', variant: 'accent' },
  'in-motion': { label: 'In Motion 30%', variant: 'rust' },
}

function getProjectStage(project: Project): (typeof STAGE_ORDER)[number] {
  return project.stage ?? (project.autoGenerated ? 'evolving' : 'released')
}

function compareProjects(left: Project, right: Project): number {
  const momentumRank: Record<NonNullable<Project['momentum']>, number> = {
    featured: 0,
    advancing: 1,
    'in-motion': 2,
  }

  const leftMomentum = momentumRank[left.momentum ?? (left.featured ? 'featured' : 'advancing')]
  const rightMomentum = momentumRank[right.momentum ?? (right.featured ? 'featured' : 'advancing')]
  if (leftMomentum !== rightMomentum) return leftMomentum - rightMomentum

  const leftPriority = left.priority ?? Number.MAX_SAFE_INTEGER
  const rightPriority = right.priority ?? Number.MAX_SAFE_INTEGER
  if (leftPriority !== rightPriority) return leftPriority - rightPriority

  const leftUpdated = left.lastUpdated ?? ''
  const rightUpdated = right.lastUpdated ?? ''
  if (leftUpdated && rightUpdated && leftUpdated !== rightUpdated) {
    return rightUpdated.localeCompare(leftUpdated)
  }

  return left.title.localeCompare(right.title)
}

export default function ProjectCollection({
  description,
  projects,
  title,
}: ProjectCollectionProps): JSX.Element {
  const [category, setCategory] = useState('All')

  const categories = useMemo(() => {
    return ['All', ...Array.from(new Set(projects.map((project) => project.category)))]
  }, [projects])

  const curated = useMemo(
    () => projects.filter((project) => !project.autoGenerated),
    [projects],
  )
  const imported = useMemo(
    () => projects.filter((project) => project.autoGenerated),
    [projects],
  )

  const filterProjects = (items: Project[]) => {
    if (category === 'All') return items
    return items.filter((project) => project.category === category)
  }

  const renderCards = (items: Project[]) => {
    const visible = filterProjects(items)
    const grouped = STAGE_ORDER.map((stage) => ({
      stage,
      projects: visible
        .filter((project) => getProjectStage(project) === stage)
        .slice()
        .sort(compareProjects),
    })).filter((group) => group.projects.length > 0)

    return (
      <div className="ds-stack">
        <div className="flex flex-wrap gap-2">
          {categories.map((item) => (
            <button
              key={item}
              type="button"
              className={`ds-button ${category === item ? 'ds-button--primary' : 'ds-button--ghost'} ds-button--sm`}
              onClick={() => setCategory(item)}
            >
              {item}
            </button>
          ))}
        </div>

        {grouped.map(({ stage, projects: stageProjects }) => {
          const stageMeta = STAGE_META[stage]

          return (
            <div key={stage} className="ds-stack ds-stack--tight">
              <div className="ds-stack ds-stack--tight" style={{ gap: '0.35rem' }}>
                <Subheading>{stageMeta.title}</Subheading>
                <Text className="ds-text--small">{stageMeta.description}</Text>
              </div>

              <div className="ds-collection-grid">
                {stageProjects.map((project) => {
                  const momentum = project.momentum
                  const momentumMeta = momentum ? MOMENTUM_META[momentum] : null

                  return (
                    <Card key={project.id} as="article" interactive className="h-full">
                      <div className="ds-stack ds-stack--tight h-full">
                        <div className="flex flex-wrap items-center gap-2">
                          {project.badge ? <Badge accent>{project.badge}</Badge> : <Badge>{project.category}</Badge>}
                          {momentumMeta ? <Badge variant={momentumMeta.variant}>{momentumMeta.label}</Badge> : null}
                          {project.autoGenerated ? <Badge>GitHub import</Badge> : null}
                        </div>

                        <Subheading>{project.title}</Subheading>
                        <Text>{project.shortDescription}</Text>

                        {project.outcome ? (
                          <Text className="ds-note">
                            {project.outcome}
                          </Text>
                        ) : null}

                        <div className="ds-chip-row">
                          {project.tech.slice(0, 4).map((tech) => (
                            <span key={tech} className="ds-tag">
                              {tech}
                            </span>
                          ))}
                        </div>

                        <div className="mt-auto flex flex-wrap gap-3 pt-2">
                          <Link href={`/projects/${project.id}`} className="ds-button ds-button--secondary ds-button--sm">
                            Case study
                          </Link>
                          {project.github ? (
                            <a
                              href={project.github}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="ds-button ds-button--ghost ds-button--sm"
                            >
                              GitHub
                            </a>
                          ) : null}
                        </div>
                      </div>
                    </Card>
                  )
                })}
              </div>
            </div>
          )
        })}
      </div>
    )
  }

  return (
    <section className="ds-section">
      <Container>
        <div className="ds-stack ds-stack--loose">
          <div className="ds-section-intro" style={{ marginBottom: 0 }}>
            <Heading>{title}</Heading>
            {description ? <Text className="max-w-3xl">{description}</Text> : null}
          </div>

          <Divider align="left" />

          <Tabs
            items={[
              {
                id: 'curated',
                label: `Curated (${curated.length})`,
                content: renderCards(curated),
              },
              {
                id: 'imports',
                label: `Public Imports (${imported.length})`,
                content: renderCards(imported),
              },
            ]}
          />

          <div className="flex flex-wrap gap-3">
            <ButtonLink href="/resume" variant="secondary" size="md">
              Open resume
            </ButtonLink>
            <ButtonLink href="/stats" variant="ghost" size="md">
              View project stats
            </ButtonLink>
          </div>
        </div>
      </Container>
    </section>
  )
}
