// Helper utilities for ChatWidget — pure functions operating on passed data
export function findProjectByIdOrName(data: any, q: string) {
  if (!data || !Array.isArray(data.projects)) return null
  const key = String(q || '').toLowerCase()
  // direct id/title match
  for (const p of data.projects) {
    if (!p) continue
    if (String(p.id).toLowerCase() === key) return p
    if (String(p.title || '').toLowerCase() === key) return p
  }
  // fuzzy substring match
  for (const p of data.projects) {
    const hay = `${p.id} ${p.title} ${p.shortDescription || ''} ${(p.tech || []).join(' ')}`.toLowerCase()
    if (hay.includes(key)) return p
  }
  return null
}

export function explainProjectText(p: any) {
  if (!p) return "I couldn't find that project."
  const parts: string[] = []
  parts.push(`${p.title || p.id}`)
  if (p.shortDescription) parts.push(`Overview: ${p.shortDescription}`)
  if (p.problem) parts.push(`Problem: ${p.problem}`)
  if (p.solution) parts.push(`Solution: ${p.solution}`)
  if (p.fullDescription && !p.solution && !p.problem) parts.push(`${p.fullDescription}`)
  if (p.tech && p.tech.length) parts.push(`Technologies: ${p.tech.join(', ')}`)
  if (p.outcome) parts.push(`Outcome: ${p.outcome}`)
  if (p.github) parts.push(`GitHub: ${p.github}`)
  if (p.lastUpdated) {
    try { parts.push(`Last updated: ${new Date(p.lastUpdated).toLocaleString()}`) } catch { parts.push(`Last updated: ${p.lastUpdated}`) }
  }
  if (p.autoGenerated) parts.push('Note: This entry was auto-generated from GitHub.')
  return parts.join('\n\n')
}

export function generateAnswerFromKnowledge(data: any, query: string) {
  if (!data) return "I couldn't load my knowledge base — try again later."
  const q = String(query || '').toLowerCase()

  const graph = data.graph || null
  if (graph && Array.isArray(graph.nodes) && Array.isArray(graph.edges)) {
    const findGraphNode = (label: string, type?: string) => {
      if (!label) return null
      const key = String(label || '').toLowerCase().trim()
      const byId = graph.nodes.find((n: any) => String(n.id || '').toLowerCase() === key || String(n.projectId || '').toLowerCase() === key)
      if (byId) return byId
      return graph.nodes.find((n: any) => {
        const candidates = [String(n.name || ''), String(n.title || ''), String(n.projectId || ''), String(n.id || '')]
        return candidates.some((c: string) => !!c && c.toLowerCase().includes(key))
      }) || null
    }

    const getProjectsUsingNode = (label: string) => {
      const node = findGraphNode(label)
      if (!node) return []
      const out: any[] = []
      for (const e of graph.edges) {
        if (String(e.rel || '').toLowerCase() !== 'uses') continue
        if (String(e.source) === node.id && String(e.target || '').startsWith('project:')) {
          const p = graph.nodes.find((n: any) => n.id === e.target)
          if (p) out.push(p)
        }
        if (String(e.target) === node.id && String(e.source || '').startsWith('project:')) {
          const p = graph.nodes.find((n: any) => n.id === e.source)
          if (p) out.push(p)
        }
      }
      return Array.from(new Map(out.map((o: any) => [o.id, o])).values())
    }

    const getNodesUsedByProject = (projectLabel: string) => {
      const pnode = findGraphNode(projectLabel, 'project')
      if (!pnode) return []
      const out: any[] = []
      for (const e of graph.edges) {
        if (String(e.rel || '').toLowerCase() !== 'uses') continue
        if (e.source === pnode.id) {
          const n = graph.nodes.find((x: any) => x.id === e.target)
          if (n) out.push(n)
        }
        if (e.target === pnode.id) {
          const n = graph.nodes.find((x: any) => x.id === e.source)
          if (n) out.push(n)
        }
      }
      return Array.from(new Map(out.map((o: any) => [o.id, o])).values())
    }

    const useMatch = q.match(/which projects (?:use|using) (.+)/) || q.match(/projects (?:that )?(?:use|using|with) (.+)/)
    if (useMatch && useMatch[1]) {
      const target = useMatch[1].replace(/\?$/, '').trim()
      const projs = getProjectsUsingNode(target)
      if (projs.length) return `Projects that use ${target}: ${projs.map((p: any) => p.title || p.projectId || p.id).join(', ')}.`
    }

    if ((q.includes('skill') || q.includes('skills') || q.includes('technology') || q.includes('technologies') || q.includes('tech')) && Array.isArray(data.projects)) {
      for (const p of data.projects) {
        const name = String(p.title || p.id || '').toLowerCase()
        if (!name) continue
        if (q.includes(name)) {
          const used = getNodesUsedByProject(p.title || p.id)
          if (used.length) {
            const skills = used.filter((n: any) => n.type === 'skill').map((s: any) => s.name || s.title || s.id)
            const techs = used.filter((n: any) => n.type === 'technology').map((s: any) => s.name || s.title || s.id)
            const parts: string[] = []
            if (skills.length) parts.push(`Skills: ${skills.join(', ')}`)
            if (techs.length) parts.push(`Technologies: ${techs.join(', ')}`)
            if (parts.length) return `${p.title || p.id} uses: ${parts.join('. ')}`
          }
        }
      }
    }

    const skillMatches = graph.nodes.filter((n: any) => (n.type === 'skill' || n.type === 'technology') && ((n.name || n.title || '').toLowerCase() && q.includes((n.name || n.title || '').toLowerCase())))
    if (skillMatches.length) {
      const first = skillMatches[0]
      const projs = getProjectsUsingNode(first.name || first.title || first.id)
      if (projs.length) return `Projects that use ${(first.name || first.title || first.id)}: ${projs.map((p: any) => p.title || p.projectId || p.id).join(', ')}.`
    }
  }

  const explainMatch = q.match(/explain(?: this| the)? project(?: for| about)?\s*(.*)/)
  if (explainMatch && explainMatch[1]) {
    const name = explainMatch[1].trim()
    const p = findProjectByIdOrName(data, name)
    return explainProjectText(p)
  }

  for (const p of data.projects) {
    if (!p) continue
    if (q.includes(String(p.id).toLowerCase()) || q.includes(String(p.title || '').toLowerCase())) {
      return explainProjectText(p)
    }
  }

  if (q.includes('projects') || q.includes('project list') || q.includes('what projects')) {
    return `I maintain projects such as: ${data.projects.map((p: any) => p.title).join(', ')}. Ask me to "Explain <project name>" for details about any project.`
  }

  if (q.includes('skill') || q.includes('skills') || data.skills.some((s: any) => q.includes(s.name.toLowerCase()))) {
    const matches = data.skills.filter((s: any) => q.includes(s.name.toLowerCase()))
    if (matches.length) return `Matching skills: ${matches.map((m: any) => `${m.name} (${m.value}%)`).join(', ')}`
    const top = data.skills.slice(0, 6).map((s: any) => `${s.name} (${s.value}%)`).join(', ')
    return `Top skills: ${top}.`
  }

  if (q.includes('experience') || q.includes('work') || q.includes('resume')) {
    const ex = data.experience.map((e: any) => `${e.title} (${e.meta}) — ${e.summary}`).join('\n')
    return `Experience:\n${ex}`
  }

  if (q.includes('navigate') || q.includes('3d') || q.includes('camera')) {
    return 'Use your mouse or touch: drag to rotate, scroll to zoom. Click a project node to focus it. Use the panels overlay to jump to sections.'
  }

  return `I can answer questions about my projects, skills, and experience. Try: "Explain Yor Zenith", "What skills do you use?", or "What's your experience?"`
}

export function simpleGenerateAnswer(data: any, query: string): string {
  if (!data) return "I couldn't load my knowledge base — try again later."
  const q = String(query || '').toLowerCase()

  for (const p of data.projects) {
    if (q.includes(p.id) || q.includes(p.title.toLowerCase())) {
      return `${p.title}: ${p.shortDescription} Technologies: ${p.tech.join(', ')}.${p.github ? ' GitHub: ' + p.github : ''}`
    }
  }

  if (q.includes('projects') || q.includes('project list') || q.includes('what projects')) {
    return `I have built projects such as ${data.projects.map((p: any) => p.title).join(', ')}. Ask me about any project by name.`
  }

  if (q.includes('skill') || q.includes('skills') || data.skills.some((s: any) => q.includes(s.name.toLowerCase()))) {
    const matches = data.skills.filter((s: any) => q.includes(s.name.toLowerCase()))
    if (matches.length) return `Matching skills: ${matches.map((m: any) => `${m.name} (${m.value}%)`).join(', ')}.`
    const top = data.skills.slice(0, 6).map((s: any) => `${s.name} (${s.value}%)`).join(', ')
    return `Top skills: ${top}.`
  }

  if (q.includes('experience') || q.includes('work') || q.includes('resume')) {
    const ex = data.experience.map((e: any) => `${e.title} (${e.meta}) — ${e.summary}`).join('\n')
    return `Experience:\n${ex}`
  }

  if (q.includes('navigate') || q.includes('3d') || q.includes('camera')) {
    return 'Use your mouse or touch: drag to rotate, scroll to zoom. Click a project node to focus it. Use the panels overlay to jump to sections.'
  }

  return `I can answer questions about my projects, skills, and experience. Try: "Tell me about Yor Zenith", "What skills do you use?", or "What's your experience?"`
}
