import {
  ACHIEVEMENT_ITEMS,
  EDUCATION_ITEMS,
  EXPERIENCE_ITEMS,
  ORDERED_PROJECTS,
  SITE_PROFILE,
} from '../data/site'

export type ResumeEntry = {
  title: string
  summary: string
  meta: string
}

export const RESUME_PROFILE = {
  name: SITE_PROFILE.name,
  role: SITE_PROFILE.role,
  summary: SITE_PROFILE.recruiterSummary,
  email: SITE_PROFILE.email,
  phone: SITE_PROFILE.phone,
  githubLabel: SITE_PROFILE.githubLabel,
  githubHref: SITE_PROFILE.githubHref,
  linkedinLabel: SITE_PROFILE.linkedinLabel,
  linkedinHref: SITE_PROFILE.linkedinHref,
} as const

export const EXPERIENCE_ENTRIES: ResumeEntry[] = EXPERIENCE_ITEMS.map((item) => ({
  title: item.title,
  summary: item.summary,
  meta: item.meta,
}))

export const EDUCATION_ENTRIES: ResumeEntry[] = EDUCATION_ITEMS.map((item) => ({
  title: item.title,
  summary: item.summary,
  meta: item.meta,
}))

export const PROJECT_ENTRIES: ResumeEntry[] = ORDERED_PROJECTS.slice(0, 4).map((project) => ({
  title: project.title,
  summary: project.shortDescription,
  meta: project.badge || (project.autoGenerated ? 'Public GitHub import' : project.category),
}))

export const RESUME_ACHIEVEMENTS = ACHIEVEMENT_ITEMS
  .filter((item) => item.id !== 'achievement-cs2')
  .map((item) => `${item.title}: ${item.detail}`)
