export type AssistantProject = {
  id: string
  title?: string
  shortDescription?: string
  problem?: string
  solution?: string
  fullDescription?: string
  tech?: string[]
  outcome?: string
  github?: string
  lastUpdated?: string
  autoGenerated?: boolean
  featured?: boolean
  category?: string
}

export type AssistantSkill = {
  name: string
  value?: number
}

export type AssistantExperience = {
  title: string
  meta?: string
  summary?: string
}

export type AssistantEducation = {
  title: string
  institution?: string
  period?: string
}

type AssistantGraphNode = {
  id: string
  type?: string
  name?: string
  title?: string
  projectId?: string
}

type AssistantGraphEdge = {
  source?: string
  target?: string
  rel?: string
}

type AssistantGraph = {
  nodes?: AssistantGraphNode[]
  edges?: AssistantGraphEdge[]
}

export type AssistantKnowledgeData = {
  profile?: {
    summary?: string
    email?: string
    phone?: string
    github?: string
    linkedin?: string
  }
  projects?: AssistantProject[]
  skills?: AssistantSkill[]
  experience?: AssistantExperience[]
  education?: AssistantEducation[]
  graph?: AssistantGraph
}

function hasText(value: unknown): value is string {
  return typeof value === 'string' && value.trim().length > 0
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function queryIncludesTerm(query: string, term: string): boolean {
  const normalizedQuery = query.toLowerCase()
  const normalizedTerm = term.trim().toLowerCase()
  if (!normalizedTerm) return false

  if (/^[a-z0-9]+$/i.test(normalizedTerm) && normalizedTerm.length <= 2) {
    const pattern = new RegExp(`(^|[^a-z0-9])${escapeRegExp(normalizedTerm)}([^a-z0-9]|$)`, 'i')
    return pattern.test(normalizedQuery)
  }

  return normalizedQuery.includes(normalizedTerm)
}

function getProjects(data: AssistantKnowledgeData | null | undefined): AssistantProject[] {
  return Array.isArray(data?.projects) ? data.projects.filter(Boolean) : []
}

function getSkills(data: AssistantKnowledgeData | null | undefined): AssistantSkill[] {
  return Array.isArray(data?.skills) ? data.skills.filter((skill) => hasText(skill?.name)) : []
}

function getExperience(data: AssistantKnowledgeData | null | undefined): AssistantExperience[] {
  return Array.isArray(data?.experience)
    ? data.experience.filter((entry) => hasText(entry?.title))
    : []
}

function getEducation(data: AssistantKnowledgeData | null | undefined): AssistantEducation[] {
  return Array.isArray(data?.education)
    ? data.education.filter((entry) => hasText(entry?.title))
    : []
}

function getGraph(data: AssistantKnowledgeData | null | undefined): Required<AssistantGraph> | null {
  const nodes = Array.isArray(data?.graph?.nodes) ? data.graph.nodes.filter(Boolean) : []
  const edges = Array.isArray(data?.graph?.edges) ? data.graph.edges.filter(Boolean) : []
  return nodes.length || edges.length ? { nodes, edges } : null
}

function getProjectDisplayName(project: AssistantProject): string {
  return hasText(project.title) ? project.title : project.id
}

function formatEducationEntry(entry: AssistantEducation): string {
  const segments = [entry.title]

  if (hasText(entry.institution)) {
    segments.push(`(${entry.institution})`)
  }

  if (hasText(entry.period)) {
    segments.push(`- ${entry.period}`)
  }

  return segments.join(' ')
}

function getExperienceAnswer(data: AssistantKnowledgeData): string {
  const sections: string[] = []
  const profileSummary = data.profile?.summary?.trim()
  const experience = getExperience(data)
  const education = getEducation(data)

  if (hasText(profileSummary)) {
    sections.push(profileSummary)
  }

  if (experience.length) {
    sections.push(
      ...experience.map((entry) => {
        const meta = hasText(entry.meta) ? ` (${entry.meta})` : ''
        const summary = hasText(entry.summary) ? ` - ${entry.summary}` : ''
        return `${entry.title}${meta}${summary}`
      }),
    )
  }

  if (education.length) {
    sections.push(...education.map(formatEducationEntry))
  }

  if (!sections.length) {
    return "I don't have detailed experience entries loaded right now, but I can still walk through my projects and skills."
  }

  return `Experience:\n${sections.join('\n')}`
}

function getContactAnswer(data: AssistantKnowledgeData): string {
  const profile = data.profile
  const lines = [
    profile?.email ? `Email: ${profile.email}` : '',
    profile?.phone ? `Phone: ${profile.phone}` : '',
    profile?.linkedin ? `LinkedIn: ${profile.linkedin}` : '',
    profile?.github ? `GitHub: ${profile.github}` : '',
  ].filter(hasText)

  if (!lines.length) {
    return "I don't have direct contact details loaded right now."
  }

  return `You can contact me here:\n${lines.join('\n')}`
}

function getProjectListAnswer(projects: AssistantProject[]): string {
  const titles = projects
    .map(getProjectDisplayName)
    .filter(hasText)

  if (!titles.length) {
    return "I don't have any project entries loaded right now."
  }

  return `I maintain projects such as: ${titles.join(', ')}. Ask me to "Explain <project name>" for details about any project.`
}

function getSkillsAnswer(skills: AssistantSkill[], query: string): string {
  if (!skills.length) {
    return "I don't have skill entries loaded right now."
  }

  const matches = skills.filter((skill) => queryIncludesTerm(query, skill.name))
  if (matches.length) {
    return `Matching skills: ${matches.map((skill) => `${skill.name} (${skill.value ?? 0}%)`).join(', ')}`
  }

  const top = skills
    .slice(0, 6)
    .map((skill) => `${skill.name} (${skill.value ?? 0}%)`)
    .join(', ')

  return `Top skills: ${top}.`
}

function findGraphNode(
  graph: Required<AssistantGraph>,
  label: string,
): AssistantGraphNode | null {
  const key = label.toLowerCase().trim()
  if (!key) return null

  const byId = graph.nodes.find((node) => {
    const id = hasText(node.id) ? node.id.toLowerCase() : ''
    const projectId = hasText(node.projectId) ? node.projectId.toLowerCase() : ''
    return id === key || projectId === key
  })
  if (byId) return byId

  return graph.nodes.find((node) => {
    const candidates = [node.name, node.title, node.projectId, node.id]
      .filter(hasText)
      .map((value) => value.toLowerCase())

    return candidates.some((candidate) => candidate.includes(key))
  }) ?? null
}

function getProjectsUsingNode(
  graph: Required<AssistantGraph>,
  label: string,
): AssistantGraphNode[] {
  const node = findGraphNode(graph, label)
  if (!node) return []

  const matches: AssistantGraphNode[] = []
  for (const edge of graph.edges) {
    if (String(edge.rel || '').toLowerCase() !== 'uses') continue

    if (String(edge.source) === node.id && String(edge.target || '').startsWith('project:')) {
      const projectNode = graph.nodes.find((candidate) => candidate.id === edge.target)
      if (projectNode) matches.push(projectNode)
    }

    if (String(edge.target) === node.id && String(edge.source || '').startsWith('project:')) {
      const projectNode = graph.nodes.find((candidate) => candidate.id === edge.source)
      if (projectNode) matches.push(projectNode)
    }
  }

  return Array.from(new Map(matches.map((match) => [match.id, match])).values())
}

function getNodesUsedByProject(
  graph: Required<AssistantGraph>,
  projectLabel: string,
): AssistantGraphNode[] {
  const projectNode = findGraphNode(graph, projectLabel)
  if (!projectNode) return []

  const matches: AssistantGraphNode[] = []
  for (const edge of graph.edges) {
    if (String(edge.rel || '').toLowerCase() !== 'uses') continue

    if (edge.source === projectNode.id) {
      const node = graph.nodes.find((candidate) => candidate.id === edge.target)
      if (node) matches.push(node)
    }

    if (edge.target === projectNode.id) {
      const node = graph.nodes.find((candidate) => candidate.id === edge.source)
      if (node) matches.push(node)
    }
  }

  return Array.from(new Map(matches.map((match) => [match.id, match])).values())
}

export function findProjectByIdOrName(
  data: AssistantKnowledgeData | null | undefined,
  query: string,
): AssistantProject | null {
  const projects = getProjects(data)
  const key = String(query || '').trim().toLowerCase()
  if (!key) return null

  for (const project of projects) {
    if (project.id.toLowerCase() === key) return project
    if (String(project.title || '').toLowerCase() === key) return project
  }

  for (const project of projects) {
    const haystack = [
      project.id,
      project.title,
      project.shortDescription,
      ...(Array.isArray(project.tech) ? project.tech : []),
    ]
      .filter(hasText)
      .join(' ')
      .toLowerCase()

    if (haystack.includes(key)) return project
  }

  return null
}

export function explainProjectText(project: AssistantProject | null | undefined): string {
  if (!project) return "I couldn't find that project."

  const parts: string[] = [getProjectDisplayName(project)]

  if (hasText(project.shortDescription)) parts.push(`Overview: ${project.shortDescription}`)
  if (hasText(project.problem)) parts.push(`Problem: ${project.problem}`)
  if (hasText(project.solution)) parts.push(`Solution: ${project.solution}`)

  if (
    hasText(project.fullDescription) &&
    !hasText(project.solution) &&
    !hasText(project.problem)
  ) {
    parts.push(project.fullDescription)
  }

  if (Array.isArray(project.tech) && project.tech.length) {
    parts.push(`Technologies: ${project.tech.join(', ')}`)
  }

  if (hasText(project.outcome)) parts.push(`Outcome: ${project.outcome}`)
  if (hasText(project.github)) parts.push(`GitHub: ${project.github}`)

  if (hasText(project.lastUpdated)) {
    const timestamp = new Date(project.lastUpdated)
    parts.push(
      Number.isNaN(timestamp.getTime())
        ? `Last updated: ${project.lastUpdated}`
        : `Last updated: ${timestamp.toLocaleString()}`,
    )
  }

  if (project.autoGenerated) {
    parts.push('Note: This entry was auto-generated from GitHub.')
  }

  return parts.join('\n\n')
}

export function generateAnswerFromKnowledge(
  data: AssistantKnowledgeData | null | undefined,
  query: string,
): string {
  if (!data) return "I couldn't load my knowledge base - try again later."

  const q = String(query || '').toLowerCase()
  const projects = getProjects(data)
  const skills = getSkills(data)
  const graph = getGraph(data)

  if (
    q.includes('contact') ||
    q.includes('email') ||
    q.includes('phone') ||
    q.includes('mobile') ||
    q.includes('call') ||
    q.includes('reach')
  ) {
    return getContactAnswer(data)
  }

  if (graph) {
    const useMatch =
      q.match(/which projects (?:use|using) (.+)/) ||
      q.match(/projects (?:that )?(?:use|using|with) (.+)/)

    if (useMatch?.[1]) {
      const target = useMatch[1].replace(/\?$/, '').trim()
      const graphProjects = getProjectsUsingNode(graph, target)
      if (graphProjects.length) {
        return `Projects that use ${target}: ${graphProjects.map((project) => project.title || project.projectId || project.id).join(', ')}.`
      }
    }

    if (
      (q.includes('skill') ||
        q.includes('skills') ||
        q.includes('technology') ||
        q.includes('technologies') ||
        q.includes('tech')) &&
      projects.length
    ) {
      for (const project of projects) {
        const name = getProjectDisplayName(project).toLowerCase()
        if (!name || !q.includes(name)) continue

        const usedNodes = getNodesUsedByProject(graph, getProjectDisplayName(project))
        if (!usedNodes.length) continue

        const skillNames = usedNodes
          .filter((node) => node.type === 'skill')
          .map((node) => node.name || node.title || node.id)
          .filter(hasText)
        const techNames = usedNodes
          .filter((node) => node.type === 'technology')
          .map((node) => node.name || node.title || node.id)
          .filter(hasText)

        const parts: string[] = []
        if (skillNames.length) parts.push(`Skills: ${skillNames.join(', ')}`)
        if (techNames.length) parts.push(`Technologies: ${techNames.join(', ')}`)
        if (parts.length) return `${getProjectDisplayName(project)} uses: ${parts.join('. ')}`
      }
    }

    const matchedNodes = graph.nodes.filter((node) => {
      if (node.type !== 'skill' && node.type !== 'technology') return false
      const label = node.name || node.title || ''
      return hasText(label) && q.includes(label.toLowerCase())
    })

    if (matchedNodes.length) {
      const firstMatch = matchedNodes[0]
      const graphProjects = getProjectsUsingNode(graph, firstMatch.name || firstMatch.title || firstMatch.id)
      if (graphProjects.length) {
        return `Projects that use ${firstMatch.name || firstMatch.title || firstMatch.id}: ${graphProjects.map((project) => project.title || project.projectId || project.id).join(', ')}.`
      }
    }
  }

  const explainMatch = q.match(/explain(?: this| the)? project(?: for| about)?\s*(.*)/)
  if (hasText(explainMatch?.[1])) {
    const project = findProjectByIdOrName(data, explainMatch[1].trim())
    return explainProjectText(project)
  }

  for (const project of projects) {
    const id = project.id.toLowerCase()
    const title = String(project.title || '').toLowerCase()
    if (q.includes(id) || (title && q.includes(title))) {
      return explainProjectText(project)
    }
  }

  if (q.includes('projects') || q.includes('project list') || q.includes('what projects')) {
    return getProjectListAnswer(projects)
  }

  const asksAboutSkills =
    q.includes('skill') ||
    q.includes('skills') ||
    skills.some((skill) => queryIncludesTerm(q, skill.name))
  if (asksAboutSkills) {
    return getSkillsAnswer(skills, q)
  }

  if (q.includes('experience') || q.includes('work') || q.includes('resume')) {
    return getExperienceAnswer(data)
  }

  if (q.includes('navigate') || q.includes('3d') || q.includes('camera')) {
    return 'Use your mouse or touch: drag to rotate, scroll to zoom. Click a project node to focus it. Use the panels overlay to jump to sections.'
  }

  return 'I can answer questions about my projects, skills, and experience. Try: "Explain Yor Zenith", "What skills do you use?", or "What\'s your experience?"'
}

export function simpleGenerateAnswer(
  data: AssistantKnowledgeData | null | undefined,
  query: string,
): string {
  if (!data) return "I couldn't load my knowledge base - try again later."

  const q = String(query || '').toLowerCase()
  const projects = getProjects(data)
  const skills = getSkills(data)

  if (
    q.includes('contact') ||
    q.includes('email') ||
    q.includes('phone') ||
    q.includes('mobile') ||
    q.includes('call') ||
    q.includes('reach')
  ) {
    return getContactAnswer(data)
  }

  for (const project of projects) {
    const title = String(project.title || '').toLowerCase()
    if (q.includes(project.id.toLowerCase()) || (title && q.includes(title))) {
      const tech = Array.isArray(project.tech) ? project.tech.join(', ') : ''
      return `${getProjectDisplayName(project)}: ${project.shortDescription || 'No description available.'}${tech ? ` Technologies: ${tech}.` : ''}${project.github ? ` GitHub: ${project.github}` : ''}`
    }
  }

  if (q.includes('projects') || q.includes('project list') || q.includes('what projects')) {
    const titles = projects.map(getProjectDisplayName).filter(hasText)
    if (!titles.length) return "I don't have any project entries loaded right now."
    return `I have built projects such as ${titles.join(', ')}. Ask me about any project by name.`
  }

  const asksAboutSkills =
    q.includes('skill') ||
    q.includes('skills') ||
    skills.some((skill) => queryIncludesTerm(q, skill.name))
  if (asksAboutSkills) {
    return getSkillsAnswer(skills, q)
  }

  if (q.includes('experience') || q.includes('work') || q.includes('resume')) {
    return getExperienceAnswer(data)
  }

  if (q.includes('navigate') || q.includes('3d') || q.includes('camera')) {
    return 'Use your mouse or touch: drag to rotate, scroll to zoom. Click a project node to focus it. Use the panels overlay to jump to sections.'
  }

  return 'I can answer questions about my projects, skills, and experience. Try: "Tell me about Yor Zenith", "What skills do you use?", or "What\'s your experience?"'
}
