import {
  EDUCATION_ITEMS,
  EXPERIENCE_ITEMS,
  ORDERED_PROJECTS,
  SITE_PROFILE,
  SKILL_CATEGORIES,
} from '../data'
import type { AssistantKnowledgeData } from './chatHelpers'

export const ASSISTANT_KNOWLEDGE: AssistantKnowledgeData = {
  profile: {
    summary: SITE_PROFILE.recruiterSummary,
  },
  projects: ORDERED_PROJECTS.map((project) => ({
    id: project.id,
    title: project.title,
    shortDescription: project.shortDescription,
    problem: project.problem,
    solution: project.solution,
    fullDescription: project.fullDescription,
    tech: project.tech,
    outcome: project.outcome,
    github: project.github,
    lastUpdated: project.lastUpdated,
    autoGenerated: project.autoGenerated,
    featured: project.featured,
    category: project.category,
  })),
  skills: Object.values(SKILL_CATEGORIES)
    .flat()
    .map((skill) => ({
      name: skill.name,
      value: skill.value,
    })),
  experience: EXPERIENCE_ITEMS.map((entry) => ({
    title: entry.title,
    meta: entry.meta,
    summary: entry.summary,
  })),
  education: EDUCATION_ITEMS.map((entry) => ({
    title: entry.title,
    institution: entry.meta,
    period: entry.dateDisplay,
  })),
}
