/**
 * data/index.ts
 *
 * Barrel file — re-exports every named export from the focused data modules so
 * existing imports like `import { GAME_LIBRARY } from '@/data/site'` keep
 * working after you update the path alias (or add `data/site` → `data/index`
 * to your tsconfig paths / next.config aliases).
 *
 * Nothing here changes the shape of the data; it only assembles the public API.
 */

export * from './personal'
export * from './projects'
export * from './achievements'
export * from './games'
export * from './gallery'
export * from './media'
export * from './blog'

// ─── Derived exports that depend on multiple modules ─────────────────────────
// HOME_METRICS references PROJECTS (from projects.ts) and SKILL_CATEGORIES
// (also from projects.ts), so it lives here rather than in personal.ts to
// avoid a circular import.

import { PROJECTS, SKILL_CATEGORIES } from './projects'

export const HOME_METRICS = [
  {
    label: 'Portfolio projects',
    value: String(PROJECTS.filter((project) => !project.autoGenerated).length).padStart(2, '0'),
  },
  { label: 'Public repos', value: '09' },
  {
    label: 'Skill signals',
    value: String(Object.values(SKILL_CATEGORIES).flat().length).padStart(2, '0'),
  },
  { label: 'Graduation', value: '2027' },
]
