// ─── Types ───────────────────────────────────────────────────────────────────

export type Project = {
  id: string
  title: string
  shortDescription: string
  fullDescription?: string
  problem?: string
  solution?: string
  challenges?: string
  tech: string[]
  outcome?: string
  screenshots?: string[]
  github?: string
  lastUpdated?: string
  date?: string
  autoGenerated?: boolean
  generatedFrom?: string
  featured?: boolean
  badge?: string
  tags?: string[]
  category: string
  stage?: 'released' | 'evolving' | 'coming-up'
  momentum?: 'featured' | 'advancing' | 'in-motion'
  priority?: number
}

export type Skill = {
  name: string
  value: number
  desc?: string
}

// ─── Projects ─────────────────────────────────────────────────────────────────

export const PROJECTS: Project[] = [
  {
    id: 'zenith',
    title: 'Yor Zenith - Solar Energy Planning & Decision Support System',
    shortDescription:
      'Full-stack solar decision platform combining rooftop feasibility, subsidy intelligence, long-term return analysis, and 3D visualization.',
    fullDescription:
      'Developed a solar planning platform to analyze rooftop feasibility and estimate solar energy generation. Built interactive 3D visualization dashboards using React and Three.js, implemented logic around rooftop parameters, solar irradiance, and subsidy estimates, and designed modular UI dashboards for solar potential analysis and forecasting.',
    problem:
      'Rooftop solar planning asks users to understand feasibility, expected generation, and subsidy impact before they can make a confident decision.',
    solution:
      'A React and Three.js interface that turns rooftop parameters, irradiance assumptions, and subsidy estimates into a clearer planning workflow.',
    challenges:
      'Balancing product clarity with domain complexity across engineering, financial, and visualization needs.',
    tech: ['Next.js', 'React', 'TypeScript', 'Three.js', 'Python'],
    outcome:
      'Created a decision-support project that connects feasibility analysis, solar generation forecasting, and dashboard visualization.',
    screenshots: [
      '/screenshots/zenith-case-screenshot.svg',
      '/screenshots/projects-screenshot.svg',
    ],
    github: 'https://github.com/yorayriniwnl/Yor-Zenith',
    lastUpdated: '2026-04-12T21:27:08Z',
    date: '2026-04-12',
    featured: true,
    badge: 'Resume Project',
    tags: ['Solar', 'Decision support', '3D UI'],
    category: 'Systems',
    stage: 'released',
    momentum: 'featured',
    priority: 2,
  },
  {
    id: 'ai-detector',
    title: 'Yor Ai vs Real Image',
    shortDescription:
      'ML pipeline to classify AI-generated vs real images using texture-based features (LBP, GLCM) and an SVM classifier.',
    fullDescription:
      'Developed a machine learning pipeline to classify AI-generated versus real photographs using OpenCV feature extraction, Scikit-Learn SVM training, Local Binary Pattern, GLCM texture analysis, and a Streamlit upload interface.',
    problem:
      'Synthetic images complicate trust, moderation, and provenance checks in visual media.',
    solution:
      'A classical computer-vision workflow pairing LBP and GLCM texture features with an SVM classifier and a Streamlit review surface.',
    challenges:
      'Keeping the detector explainable and lightweight without relying on heavy deep-learning infrastructure.',
    tech: ['Python', 'OpenCV', 'Scikit-Learn', 'Streamlit'],
    outcome:
      'Demonstrated an end-to-end image classification pipeline with texture features, model training, and user-facing prediction review.',
    screenshots: ['/screenshots/projects-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/Yor-Ai-vs-real-image',
    lastUpdated: '2026-04-12T21:25:14Z',
    date: '2026-04-12',
    featured: true,
    badge: 'Resume Project',
    tags: ['Computer vision', 'Image classification'],
    category: 'AI / ML',
    stage: 'released',
    momentum: 'featured',
    priority: 3,
  },
  {
    id: 'mentor-mentee',
    title: 'Yor Mentor Mentee System',
    shortDescription:
      'Full-stack mentorship workflow system with weighted matching, Flask APIs, SQLite persistence, and a Tkinter desktop interface.',
    fullDescription:
      'A GitHub-published mentor-mentee system with a Flask API layer, shared matching logic, SQLite-backed persistence, and a Tkinter desktop interface for local institutional use.',
    problem:
      'Mentoring programs often rely on manual spreadsheets and uneven matching decisions.',
    solution:
      'A lightweight Python system that centralizes mentor and mentee records, supports compatibility scoring, and exposes both API and desktop workflows.',
    challenges:
      'Designing a system that respects both human relationships and operational constraints.',
    tech: ['Python', 'Flask', 'SQLite', 'Tkinter', 'SQLAlchemy'],
    outcome:
      'Converted a manual coordination problem into a structured tool with reusable matching logic.',
    screenshots: ['/screenshots/projects-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/mentor-mentee-system',
    lastUpdated: '2026-04-13T12:59:06Z',
    date: '2026-04-13',
    featured: true,
    badge: 'Released Build',
    tags: ['Workflow', 'Mentorship'],
    category: 'Python',
    stage: 'released',
    momentum: 'featured',
    priority: 4,
  },
  {
    id: 'yor-smriti',
    title: 'Yor Smriti',
    shortDescription:
      'Narrative-first web experience for memories, timelines, private storytelling, and emotionally aware UI presentation.',
    fullDescription:
      'A TypeScript web project published on GitHub that builds a private, cinematic storytelling surface around memories, timelines, themes, templates, and shareable emotional experiences.',
    problem:
      'Personal messages and memory-based experiences can feel flat when they are presented as plain text.',
    solution:
      'A web-native storytelling interface that uses themes, templates, timeline structure, and interaction design to make private messages feel more intentional.',
    challenges:
      'Balancing emotion, privacy, and interface polish without overcomplicating the experience.',
    tech: ['TypeScript', 'JavaScript', 'CSS', 'Vercel'],
    outcome:
      'Expanded the GitHub portfolio with an expressive frontend project centered on narrative UI.',
    screenshots: ['/screenshots/projects-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/Yor-Smriti',
    lastUpdated: '2026-04-13T10:31:45Z',
    date: '2026-04-13',
    badge: 'Released Build',
    tags: ['Storytelling', 'Frontend'],
    category: 'Web',
    stage: 'released',
    momentum: 'featured',
    priority: 5,
  },
  {
    id: 'yor-ayrin-iwnl',
    title: 'Yor Ayrin iwnl',
    shortDescription:
      'The current portfolio platform: a Next.js system for case studies, recruiter-ready resume surfaces, GitHub activity, games, and interactive identity storytelling.',
    fullDescription:
      'The current public repository for this portfolio system, described on GitHub as an intelligent web-native learning system focused on adaptive experiences and dynamic content flow.',
    problem:
      'A portfolio can become static and disconnected from the project evidence it is meant to present.',
    solution:
      'A TypeScript and Next.js site that organizes profile data, project pages, resume surfaces, GitHub imports, and interactive experiences into one web-native system.',
    challenges:
      'Keeping the system accurate while multiple pages, generated data, and static surfaces refer to the same profile.',
    tech: ['Next.js', 'TypeScript', 'React', 'Framer Motion', 'Vercel'],
    outcome:
      'Established the portfolio itself as a maintained software project backed by public GitHub history.',
    screenshots: ['/screenshots/hero-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/Yor-Ayrin-iwnl',
    lastUpdated: '2026-04-13T13:35:34Z',
    date: '2026-04-13',
    badge: 'Current Site',
    tags: ['Portfolio', 'Next.js'],
    category: 'Web',
    stage: 'released',
    momentum: 'featured',
    priority: 1,
  },
  {
    id: 'yor-feelings',
    title: 'Yor Feelings',
    shortDescription:
      'Campus-social product direction exploring anonymous posting, moderation, reactions, realtime threads, and emotionally aware UX.',
    fullDescription:
      'A TypeScript frontend project with a KIIT anonymous communication platform direction, including OTP login, anonymous onboarding, threads, reactions, reports, AI moderation, sentiment, realtime messaging, and campus pulse features.',
    problem:
      'Campus communication tools need privacy, moderation, and enough emotional nuance to feel safe for users.',
    solution:
      'A TypeScript web app concept with KIIT email OTP login, anonymous threads, reactions, reports, AI moderation, sentiment, and realtime messaging.',
    challenges:
      'Combining anonymity with trust, moderation, and responsible communication flows.',
    tech: ['TypeScript', 'Next.js', 'React', 'Realtime'],
    github: 'https://github.com/yorayriniwnl/Yor-Feelings',
    lastUpdated: '2026-04-12T21:30:49Z',
    date: '2026-04-12',
    badge: 'GitHub Project',
    tags: ['Frontend', 'Realtime'],
    category: 'Web',
    stage: 'evolving',
    momentum: 'advancing',
    priority: 7,
  },
  {
    id: 'yor-helios',
    title: 'Yor Helios',
    shortDescription:
      'Energy-monitoring platform with FastAPI ingestion, anomaly detection, WebSocket alerts, map visualizations, and Next.js dashboards.',
    fullDescription:
      'Helios is a modern energy-monitoring platform that detects anomalies in meter readings, surfaces realtime alerts, and provides dashboards for operators and stakeholders. The GitHub README describes FastAPI, SQLAlchemy, WebSocket alerts, Next.js, TypeScript, Tailwind CSS, Recharts, Leaflet, and Docker Compose support.',
    problem:
      'Energy operators need faster ways to identify anomalous readings, triage alerts, and understand usage patterns across meters and zones.',
    solution:
      'A backend/frontend platform with anomaly detection, realtime alert streams, KPI dashboards, geospatial heatmaps, and demo-mode data.',
    challenges:
      'Presenting noisy meter data as clear operational signals while keeping the system demoable and locally runnable.',
    tech: ['FastAPI', 'Next.js', 'TypeScript', 'PostgreSQL', 'WebSocket', 'Docker'],
    outcome:
      'Added a backend-heavy systems project to the GitHub portfolio around operational energy intelligence.',
    screenshots: ['/screenshots/projects-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/Yor-Helios',
    lastUpdated: '2026-04-12T21:29:48Z',
    date: '2026-04-12',
    badge: 'GitHub Project',
    tags: ['Energy', 'Backend'],
    category: 'Systems',
    stage: 'evolving',
    momentum: 'advancing',
    priority: 6,
  },
  {
    id: 'yor-status',
    title: 'Yor Status',
    shortDescription:
      'Public accountability platform that tracks government promises vs completions in realtime, with verified-community discussion for KIIT students.',
    fullDescription:
      'Yor-Status is a live public-status product sharing the same frontend and backend foundation style as Yor ecosystem projects. It tracks what government has promised, how much has actually been completed over time, and supports chat-based civic discussion for verified public accounts, currently focused on the KIIT student community.',
    problem:
      'Civic promises and completion claims are difficult to validate in one place, and student communities often discuss progress without a shared live source of truth.',
    solution:
      'A realtime tracking interface with promise/completion visibility and verified-account chat so users can review progress and discuss policy outcomes with clearer context.',
    challenges:
      'Maintaining trust in live civic data while balancing verification, moderation, and a clear product experience for active public discussion.',
    tech: ['TypeScript', 'React', 'Next.js', 'Node.js'],
    outcome:
      'Adds a civic-tech accountability signal to the verified portfolio set with live progress tracking and verified public chat workflows.',
    screenshots: ['/screenshots/projects-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/Yor-Status',
    badge: 'GitHub Project',
    tags: ['Civic tech', 'Realtime tracking', 'Verified chat'],
    category: 'Web',
    stage: 'coming-up',
    momentum: 'in-motion',
    priority: 8,
  },
  {
    id: 'yor-talks',
    title: 'Yor Talks',
    shortDescription:
      'Premium social platform concept positioned as an Indian-polished alternative to Instagram with cleaner UX and product-first storytelling.',
    fullDescription:
      'Yor-Talks is a premium social product direction focused on polished interaction design, stronger creator presentation, and cleaner discovery surfaces tuned for an Indian audience. The goal is to keep social posting expressive while improving content quality and interface clarity.',
    problem:
      'Mainstream social feeds often prioritize noise and repetition over polished creator identity and meaningful discovery.',
    solution:
      'A premium visual system and product flow that treats posting, profile surfaces, and social discovery as curated experiences instead of endless generic scrolling.',
    challenges:
      'Balancing familiar social patterns with a differentiated premium UX direction and region-aware product positioning.',
    tech: ['TypeScript', 'React', 'Next.js', 'CSS'],
    outcome:
      'Adds a social product signal to the verified portfolio set with an India-focused premium positioning narrative.',
    screenshots: ['/screenshots/projects-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/Yor-Talks',
    badge: 'GitHub Project',
    tags: ['Social product', 'Premium UX', 'India focus'],
    category: 'Web',
    stage: 'coming-up',
    momentum: 'in-motion',
    priority: 9,
  },
]

export const ORDERED_PROJECTS = PROJECTS.slice().sort((left, right) => {
  if (left.autoGenerated && !right.autoGenerated) return 1
  if (!left.autoGenerated && right.autoGenerated) return -1
  if (left.featured && !right.featured) return -1
  if (!left.featured && right.featured) return 1
  return left.title.localeCompare(right.title)
})

// ─── Skills ───────────────────────────────────────────────────────────────────

export const SKILL_CATEGORIES: Record<string, Skill[]> = {
  Frontend: [
    {
      name: 'React',
      value: 82,
      desc: 'Used for Yor Zenith dashboards and portfolio UI surfaces.',
    },
    {
      name: 'HTML / CSS / TailwindCSS',
      value: 82,
      desc: 'Resume-listed web development stack for responsive UI work.',
    },
    {
      name: 'TypeScript',
      value: 65,
      desc: 'Listed as basic in the resume and used across multiple public TypeScript repositories.',
    },
    {
      name: 'Three.js',
      value: 72,
      desc: 'Used for Yor Zenith 3D visualization dashboards and interactive portfolio work.',
    },
  ],
  'ML / CV': [
    {
      name: 'Python',
      value: 84,
      desc: 'Primary language for ML, computer vision, and Python systems projects.',
    },
    {
      name: 'OpenCV',
      value: 76,
      desc: 'Image feature extraction for Yor Ai vs Real Image.',
    },
    {
      name: 'Scikit-Learn',
      value: 74,
      desc: 'SVM training and model evaluation for image classification.',
    },
    {
      name: 'Streamlit',
      value: 70,
      desc: 'Used to build the image upload and prediction review interface.',
    },
  ],
  Backend: [
    {
      name: 'Next.js',
      value: 78,
      desc: 'Primary framework for this portfolio and the Yor ecosystem web products.',
    },
    {
      name: 'Flask',
      value: 70,
      desc: 'API layer for the mentor-mentee Python system.',
    },
    {
      name: 'FastAPI',
      value: 68,
      desc: 'Backend framework for Yor Helios energy-monitoring platform.',
    },
    {
      name: 'SQLite / SQLAlchemy',
      value: 62,
      desc: 'Database layer used in the mentor-mentee system and basic SQL project work.',
    },
  ],
  Tools: [
    {
      name: 'Git / GitHub',
      value: 90,
      desc: 'Public repositories, version control, project documentation, and portfolio visibility.',
    },
    {
      name: 'VS Code',
      value: 88,
      desc: 'Primary development environment across the resume and GitHub projects.',
    },
    {
      name: 'SQL',
      value: 58,
      desc: 'Basic database knowledge from the resume, reinforced by SQLite-backed project work.',
    },
  ],
  Languages: [
    {
      name: 'Python',
      value: 84,
      desc: 'Most-used language for ML, scripting, and backend-oriented projects.',
    },
    {
      name: 'Java',
      value: 52,
      desc: 'Basic programming knowledge listed in the resume.',
    },
    {
      name: 'C',
      value: 50,
      desc: 'Basic programming knowledge listed in the resume.',
    },
  ],
}
