import { PROFILE_AVATAR_SRC } from '../lib/profilePhoto'

export type Project = {
  id: string
  title: string
  shortDescription: string
  fullDescription?: string
  problem?: string
  solution?: string
  challenges?: string
  tech: string[]
  outcome?: string
  screenshots?: string[]
  github?: string
  lastUpdated?: string
  date?: string
  autoGenerated?: boolean
  generatedFrom?: string
  featured?: boolean
  badge?: string
  tags?: string[]
  category: string
  stage?: 'released' | 'evolving' | 'coming-up'
  momentum?: 'featured' | 'advancing' | 'in-motion'
  priority?: number
}

export type Skill = {
  name: string
  value: number
  desc?: string
}

export type NavLink = {
  label: string
  href: string
  external?: boolean
}

export type NavMenuGroup = {
  title: string
  links: NavLink[]
}

export type ExperienceItem = {
  id: string
  title: string
  meta: string
  summary: string
  bullets: string[]
  kind: 'verified' | 'placeholder' | 'education'
  date?: string
  dateDisplay?: string
}

export type AchievementItem = {
  id: string
  title: string
  detail: string
  label: string
  kind: 'verified' | 'placeholder'
  href?: string
  date?: string
  dateDisplay?: string
}

export type GameEntry = {
  id: string
  title: string
  subtitle: string
  status: string
  mode: 'playable' | 'showcase' | 'placeholder'
  metric: string
  detail: string
  href?: string
}

export type GalleryAsset = {
  id: string
  title: string
  src: string
  caption: string
  tag: string
}

export type MediaItem = {
  id: string
  title: string
  href: string
  summary: string
  kind: 'document' | 'demo' | 'image'
}

export type BlogNote = {
  category: string
  date: string
  excerpt: string
  featured?: boolean
  readTime: string
  title: string
  tone: 'life' | 'personal' | 'real' | 'thoughts'
}

export type YouTubeVideo = {
  id: string
  title: string
  duration: string
  thumbnail: string
  note?: string
}

export const SITE_PROFILE = {
  name: 'Ayush Roy',
  alias: 'Yor Ayrin Iwnl',
  role: 'Founder of Yor Zenith - Full Stack Developer Intern Candidate',
  summary:
    'Founder of Yor Zenith and a full-stack focused B.Tech Computer Science and Communication Engineering student at KIIT building Next.js product surfaces, Python backend systems, realtime dashboards, computer-vision tools, and interactive web experiences.',
  recruiterSummary:
    'Founder of Yor Zenith and full-stack developer intern candidate at KIIT, expected graduation 2027, with hands-on project work across Next.js, React, TypeScript, FastAPI, Flask, Python, SQL, Three.js, OpenCV, Scikit-Learn, Docker, and GitHub-driven product delivery.',
  seekingStatement: 'I am currently seeking full stack developer internship opportunities where product thinking and engineering execution both matter.',
  availability: 'Open to internships, entry-level software roles, and remote collaboration.',
  email: 'yorayriniwnl@gmail.com',
  phone: '+91 8918940799',
  githubLabel: 'github.com/yorayriniwnl',
  githubHref: 'https://github.com/yorayriniwnl',
  linkedinLabel: 'linkedin.com/in/yorayriniwnl',
  linkedinHref: 'https://linkedin.com/in/yorayriniwnl',
  steamLabel: 'steamcommunity.com/id/YorAyriniwnl',
  steamHref: process.env.NEXT_PUBLIC_STEAM_PROFILE_URL ?? 'https://steamcommunity.com/id/YorAyriniwnl',
  websiteLabel: 'yorayriniwnl.vercel.app',
  websiteHref: 'https://yorayriniwnl.vercel.app',
  avatarSrc: PROFILE_AVATAR_SRC,
} as const

export const SITE_LINKS = [
  { id: 'github', label: SITE_PROFILE.githubLabel, href: SITE_PROFILE.githubHref },
  { id: 'linkedin', label: SITE_PROFILE.linkedinLabel, href: SITE_PROFILE.linkedinHref },
  { id: 'email', label: SITE_PROFILE.email, href: `mailto:${SITE_PROFILE.email}` },
  { id: 'phone', label: SITE_PROFILE.phone, href: `tel:${SITE_PROFILE.phone.replace(/\s+/g, '')}` },
  { id: 'resume', label: 'Resume PDF', href: '/resume.pdf' },
] as const

export const NAV_LINKS: NavLink[] = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  { label: 'Projects', href: '/projects' },
  { label: 'Experience', href: '/experience' },
  { label: 'Skills', href: '/skills' },
  { label: 'Games', href: '/games' },
  { label: 'Contact', href: '/contact' },
]

export const NAV_MENU_GROUPS: NavMenuGroup[] = [
  {
    title: 'Core',
    links: [
      { label: 'About', href: '/about' },
      { label: 'Projects', href: '/projects' },
      { label: 'Experience', href: '/experience' },
      { label: 'Skills', href: '/skills' },
      { label: 'Contact', href: '/contact' },
    ],
  },
  {
    title: 'Profile',
    links: [
      { label: 'Resume', href: '/resume' },
      { label: 'CV', href: '/cv' },
      { label: 'Stats', href: '/stats' },
      { label: 'Timeline', href: '/timeline' },
      { label: 'Dashboard', href: '/dashboard' },
      { label: 'Profile', href: '/profile' },
      { label: 'Search', href: '/search' },
      { label: 'Onboarding', href: '/onboarding' },
    ],
  },
  {
    title: 'Explore',
    links: [
      { label: 'Games', href: '/games' },
      { label: 'Achievements', href: '/achievements' },
      { label: 'Blog', href: '/blog' },
      { label: 'DevLog', href: '/devlog' },
      { label: 'Gallery', href: '/gallery' },
      { label: 'Media', href: '/media' },
      { label: 'Steam', href: '/steam' },
      { label: 'Hobbies', href: '/hobbies' },
      { label: 'Fun', href: '/fun' },
      { label: 'Value Education', href: '/value-education' },
      { label: 'Settings', href: '/settings' },
    ],
  },
  {
    title: 'Labs',
    links: [
      { label: 'Avatar', href: '/avatar' },
      { label: '3D Demo', href: '/three-demo' },
    ],
  },
]

export const FOOTER_LINK_GROUPS: Record<'primary' | 'product' | 'resources', NavLink[]> = {
  primary: [
    { label: 'About', href: '/about' },
    { label: 'Projects', href: '/projects' },
    { label: 'Experience', href: '/experience' },
    { label: 'Skills', href: '/skills' },
    { label: 'Contact', href: '/contact' },
  ],
  product: [
    { label: 'Games', href: '/games' },
    { label: 'Achievements', href: '/achievements' },
    { label: 'Stats', href: '/stats' },
    { label: 'Timeline', href: '/timeline' },
    { label: 'Dashboard', href: '/dashboard' },
    { label: 'Profile', href: '/profile' },
    { label: 'Search', href: '/search' },
    { label: 'Onboarding', href: '/onboarding' },
  ],
  resources: [
    { label: 'Resume', href: '/resume' },
    { label: 'CV', href: '/cv' },
    { label: 'Blog', href: '/blog' },
    { label: 'DevLog', href: '/devlog' },
    { label: 'Gallery', href: '/gallery' },
    { label: 'Media', href: '/media' },
    { label: 'Steam', href: '/steam' },
    { label: 'Hobbies', href: '/hobbies' },
    { label: 'Fun', href: '/fun' },
    { label: 'Value Education', href: '/value-education' },
    { label: 'Avatar', href: '/avatar' },
    { label: '3D Demo', href: '/three-demo' },
    { label: 'Settings', href: '/settings' },
    { label: 'GitHub', href: SITE_PROFILE.githubHref, external: true },
  ],
}

export const PROJECTS: Project[] = [
  {
    id: 'zenith',
    title: 'Yor Zenith - Solar Energy Planning & Decision Support System',
    shortDescription:
      'Full-stack solar decision platform combining rooftop feasibility, subsidy intelligence, long-term return analysis, and 3D visualization.',
    fullDescription:
      'Developed a solar planning platform to analyze rooftop feasibility and estimate solar energy generation. Built interactive 3D visualization dashboards using React and Three.js, implemented logic around rooftop parameters, solar irradiance, and subsidy estimates, and designed modular UI dashboards for solar potential analysis and forecasting.',
    problem:
      'Rooftop solar planning asks users to understand feasibility, expected generation, and subsidy impact before they can make a confident decision.',
    solution:
      'A React and Three.js interface that turns rooftop parameters, irradiance assumptions, and subsidy estimates into a clearer planning workflow.',
    challenges:
      'Balancing product clarity with domain complexity across engineering, financial, and visualization needs.',
    tech: ['Next.js', 'React', 'TypeScript', 'Three.js', 'Python'],
    outcome:
      'Created a decision-support project that connects feasibility analysis, solar generation forecasting, and dashboard visualization.',
    screenshots: [
      '/screenshots/zenith-case-screenshot.svg',
      '/screenshots/projects-screenshot.svg',
    ],
    github: 'https://github.com/yorayriniwnl/Yor-Zenith',
    lastUpdated: '2026-04-12T21:27:08Z',
    date: '2026-04-12',
    featured: true,
    badge: 'Resume Project',
    tags: ['Solar', 'Decision support', '3D UI'],
    category: 'Systems',
    stage: 'released',
    momentum: 'featured',
    priority: 2,
  },
  {
    id: 'ai-detector',
    title: 'Yor AI vs Real Image',
    shortDescription:
      'ML pipeline to classify AI-generated vs real images using texture-based features (LBP, GLCM) and an SVM classifier.',
    fullDescription:
      'Developed a machine learning pipeline to classify AI-generated versus real photographs using OpenCV feature extraction, Scikit-Learn SVM training, Local Binary Pattern, GLCM texture analysis, and a Streamlit upload interface.',
    problem:
      'Synthetic images complicate trust, moderation, and provenance checks in visual media.',
    solution:
      'A classical computer-vision workflow pairing LBP and GLCM texture features with an SVM classifier and a Streamlit review surface.',
    challenges:
      'Keeping the detector explainable and lightweight without relying on heavy deep-learning infrastructure.',
    tech: ['Python', 'OpenCV', 'Scikit-Learn', 'Streamlit'],
    outcome:
      'Demonstrated an end-to-end image classification pipeline with texture features, model training, and user-facing prediction review.',
    screenshots: ['/screenshots/projects-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/Yor-Ai-vs-real-image',
    lastUpdated: '2026-04-12T21:25:14Z',
    date: '2026-04-12',
    featured: true,
    badge: 'Resume Project',
    tags: ['Computer vision', 'Image classification'],
    category: 'AI / ML',
    stage: 'released',
    momentum: 'featured',
    priority: 3,
  },
  {
    id: 'mentor-mentee',
    title: 'Yor Mentor Mentee System',
    shortDescription:
      'Full-stack mentorship workflow system with weighted matching, Flask APIs, SQLite persistence, and a Tkinter desktop interface.',
    fullDescription:
      'A GitHub-published mentor-mentee system with a Flask API layer, shared matching logic, SQLite-backed persistence, and a Tkinter desktop interface for local institutional use.',
    problem:
      'Mentoring programs often rely on manual spreadsheets and uneven matching decisions.',
    solution:
      'A lightweight Python system that centralizes mentor and mentee records, supports compatibility scoring, and exposes both API and desktop workflows.',
    challenges:
      'Designing a system that respects both human relationships and operational constraints.',
    tech: ['Python', 'Flask', 'SQLite', 'Tkinter', 'SQLAlchemy'],
    outcome:
      'Converted a manual coordination problem into a structured tool with reusable matching logic.',
    screenshots: ['/screenshots/projects-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/mentor-mentee-system',
    lastUpdated: '2026-04-13T12:59:06Z',
    date: '2026-04-13',
    featured: true,
    badge: 'Released Build',
    tags: ['Workflow', 'Mentorship'],
    category: 'Python',
    stage: 'released',
    momentum: 'featured',
    priority: 4,
  },
  {
    id: 'yor-smriti',
    title: 'Yor Smriti',
    shortDescription:
      'Narrative-first web experience for memories, timelines, private storytelling, and emotionally aware UI presentation.',
    fullDescription:
      'A TypeScript web project published on GitHub that builds a private, cinematic storytelling surface around memories, timelines, themes, templates, and shareable emotional experiences.',
    problem:
      'Personal messages and memory-based experiences can feel flat when they are presented as plain text.',
    solution:
      'A web-native storytelling interface that uses themes, templates, timeline structure, and interaction design to make private messages feel more intentional.',
    challenges:
      'Balancing emotion, privacy, and interface polish without overcomplicating the experience.',
    tech: ['TypeScript', 'JavaScript', 'CSS', 'Vercel'],
    outcome:
      'Expanded the GitHub portfolio with an expressive frontend project centered on narrative UI.',
    screenshots: ['/screenshots/projects-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/Yor-Smriti',
    lastUpdated: '2026-04-13T10:31:45Z',
    date: '2026-04-13',
    badge: 'Released Build',
    tags: ['Storytelling', 'Frontend'],
    category: 'Web',
    stage: 'released',
    momentum: 'featured',
    priority: 5,
  },
  {
    id: 'yor-ayrin-iwnl',
    title: 'Yor Ayrin iwnl',
    shortDescription:
      'The current portfolio platform: a Next.js system for case studies, recruiter-ready resume surfaces, GitHub activity, games, and interactive identity storytelling.',
    fullDescription:
      'The current public repository for this portfolio system, described on GitHub as an intelligent web-native learning system focused on adaptive experiences and dynamic content flow.',
    problem:
      'A portfolio can become static and disconnected from the project evidence it is meant to present.',
    solution:
      'A TypeScript and Next.js site that organizes profile data, project pages, resume surfaces, GitHub imports, and interactive experiences into one web-native system.',
    challenges:
      'Keeping the system accurate while multiple pages, generated data, and static surfaces refer to the same profile.',
    tech: ['Next.js', 'TypeScript', 'React', 'Framer Motion', 'Vercel'],
    outcome:
      'Established the portfolio itself as a maintained software project backed by public GitHub history.',
    screenshots: ['/screenshots/hero-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/Yor-Ayrin-iwnl',
    lastUpdated: '2026-04-13T13:35:34Z',
    date: '2026-04-13',
    badge: 'Current Site',
    tags: ['Portfolio', 'Next.js'],
    category: 'Web',
    stage: 'released',
    momentum: 'featured',
    priority: 1,
  },
  {
    id: 'yor-feelings',
    title: 'Yor Feelings',
    shortDescription:
      'Campus-social product direction exploring anonymous posting, moderation, reactions, realtime threads, and emotionally aware UX.',
    fullDescription:
      'A TypeScript frontend project with a KIIT anonymous communication platform direction, including OTP login, anonymous onboarding, threads, reactions, reports, AI moderation, sentiment, realtime messaging, and campus pulse features.',
    problem:
      'Campus communication tools need privacy, moderation, and enough emotional nuance to feel safe for users.',
    solution:
      'A TypeScript web app concept with KIIT email OTP login, anonymous threads, reactions, reports, AI moderation, sentiment, and realtime messaging.',
    challenges:
      'Combining anonymity with trust, moderation, and responsible communication flows.',
    tech: ['TypeScript', 'Next.js', 'React', 'Realtime'],
    github: 'https://github.com/yorayriniwnl/Yor-Feelings',
    lastUpdated: '2026-04-12T21:30:49Z',
    date: '2026-04-12',
    badge: 'GitHub Project',
    tags: ['Frontend', 'Realtime'],
    category: 'Web',
    stage: 'evolving',
    momentum: 'advancing',
    priority: 7,
  },
  {
    id: 'yor-helios',
    title: 'Yor Helios',
    shortDescription:
      'Energy-monitoring platform with FastAPI ingestion, anomaly detection, WebSocket alerts, map visualizations, and Next.js dashboards.',
    fullDescription:
      'Helios is a modern energy-monitoring platform that detects anomalies in meter readings, surfaces realtime alerts, and provides dashboards for operators and stakeholders. The GitHub README describes FastAPI, SQLAlchemy, WebSocket alerts, Next.js, TypeScript, Tailwind CSS, Recharts, Leaflet, and Docker Compose support.',
    problem:
      'Energy operators need faster ways to identify anomalous readings, triage alerts, and understand usage patterns across meters and zones.',
    solution:
      'A backend/frontend platform with anomaly detection, realtime alert streams, KPI dashboards, geospatial heatmaps, and demo-mode data.',
    challenges:
      'Presenting noisy meter data as clear operational signals while keeping the system demoable and locally runnable.',
    tech: ['FastAPI', 'Next.js', 'TypeScript', 'PostgreSQL', 'WebSocket', 'Docker'],
    outcome:
      'Added a backend-heavy systems project to the GitHub portfolio around operational energy intelligence.',
    screenshots: ['/screenshots/projects-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/Yor-Helios',
    lastUpdated: '2026-04-12T21:29:48Z',
    date: '2026-04-12',
    badge: 'GitHub Project',
    tags: ['Energy', 'Backend'],
    category: 'Systems',
    stage: 'evolving',
    momentum: 'advancing',
    priority: 6,
  },
  {
    id: 'yor-status',
    title: 'Yor Status',
    shortDescription:
      'Public accountability platform that tracks government promises vs completions in realtime, with verified-community discussion for KIIT students.',
    fullDescription:
      'Yor-Status is a live public-status product sharing the same frontend and backend foundation style as Yor ecosystem projects. It tracks what government has promised, how much has actually been completed over time, and supports chat-based civic discussion for verified public accounts, currently focused on the KIIT student community.',
    problem:
      'Civic promises and completion claims are difficult to validate in one place, and student communities often discuss progress without a shared live source of truth.',
    solution:
      'A realtime tracking interface with promise/completion visibility and verified-account chat so users can review progress and discuss policy outcomes with clearer context.',
    challenges:
      'Maintaining trust in live civic data while balancing verification, moderation, and a clear product experience for active public discussion.',
    tech: ['TypeScript', 'React', 'Next.js', 'Node.js'],
    outcome:
      'Adds a civic-tech accountability signal to the verified portfolio set with live progress tracking and verified public chat workflows.',
    screenshots: ['/screenshots/projects-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/Yor-Status',
    badge: 'GitHub Project',
    tags: ['Civic tech', 'Realtime tracking', 'Verified chat'],
    category: 'Web',
    stage: 'coming-up',
    momentum: 'in-motion',
    priority: 8,
  },
  {
    id: 'yor-talks',
    title: 'Yor Talks',
    shortDescription:
      'Premium social platform concept positioned as an Indian-polished alternative to Instagram with cleaner UX and product-first storytelling.',
    fullDescription:
      'Yor-Talks is a premium social product direction focused on polished interaction design, stronger creator presentation, and cleaner discovery surfaces tuned for an Indian audience. The goal is to keep social posting expressive while improving content quality and interface clarity.',
    problem:
      'Mainstream social feeds often prioritize noise and repetition over polished creator identity and meaningful discovery.',
    solution:
      'A premium visual system and product flow that treats posting, profile surfaces, and social discovery as curated experiences instead of endless generic scrolling.',
    challenges:
      'Balancing familiar social patterns with a differentiated premium UX direction and region-aware product positioning.',
    tech: ['TypeScript', 'React', 'Next.js', 'CSS'],
    outcome:
      'Adds a social product signal to the verified portfolio set with an India-focused premium positioning narrative.',
    screenshots: ['/screenshots/projects-screenshot.svg'],
    github: 'https://github.com/yorayriniwnl/Yor-Talks',
    badge: 'GitHub Project',
    tags: ['Social product', 'Premium UX', 'India focus'],
    category: 'Web',
    stage: 'coming-up',
    momentum: 'in-motion',
    priority: 9,
  },
]

export const ORDERED_PROJECTS = PROJECTS.slice().sort((left, right) => {
  if (left.autoGenerated && !right.autoGenerated) return 1
  if (!left.autoGenerated && right.autoGenerated) return -1
  if (left.featured && !right.featured) return -1
  if (!left.featured && right.featured) return 1
  return left.title.localeCompare(right.title)
})

export const SKILL_CATEGORIES: Record<string, Skill[]> = {
  Frontend: [
    {
      name: 'React',
      value: 82,
      desc: 'Used for Yor Zenith dashboards and portfolio UI surfaces.',
    },
    {
      name: 'HTML / CSS / TailwindCSS',
      value: 82,
      desc: 'Resume-listed web development stack for responsive UI work.',
    },
    {
      name: 'TypeScript',
      value: 65,
      desc: 'Listed as basic in the resume and used across multiple public TypeScript repositories.',
    },
    {
      name: 'Three.js',
      value: 72,
      desc: 'Used for Yor Zenith 3D visualization dashboards and interactive portfolio work.',
    },
  ],
  'ML / CV': [
    {
      name: 'Python',
      value: 84,
      desc: 'Primary language for ML, computer vision, and Python systems projects.',
    },
    {
      name: 'OpenCV',
      value: 76,
      desc: 'Image feature extraction for Yor AI vs Real Image.',
    },
    {
      name: 'Scikit-Learn',
      value: 74,
      desc: 'SVM training and model evaluation for image classification.',
    },
    {
      name: 'Streamlit',
      value: 70,
      desc: 'Used to build the image upload and prediction review interface.',
    },
  ],
  Tools: [
    {
      name: 'Git / GitHub',
      value: 90,
      desc: 'Public repositories, version control, project documentation, and portfolio visibility.',
    },
    {
      name: 'VS Code',
      value: 88,
      desc: 'Primary development environment across the resume and GitHub projects.',
    },
    {
      name: 'SQL',
      value: 58,
      desc: 'Basic database knowledge from the resume, reinforced by SQLite-backed project work.',
    },
  ],
  Languages: [
    {
      name: 'Python',
      value: 84,
      desc: 'Most-used language for ML, scripting, and backend-oriented projects.',
    },
    {
      name: 'Java',
      value: 52,
      desc: 'Basic programming knowledge listed in the resume.',
    },
    {
      name: 'C',
      value: 50,
      desc: 'Basic programming knowledge listed in the resume.',
    },
  ],
}

export const SECTIONS = [
  { id: 'home', label: 'Home', href: '/' },
  { id: 'projects', label: 'Projects', href: '/projects' },
  { id: 'experience', label: 'Experience', href: '/experience' },
  { id: 'skills', label: 'Skills', href: '/skills' },
  { id: 'contact', label: 'Contact', href: '/contact' },
]

export const EXPERIENCE_ITEMS: ExperienceItem[] = [
  {
    id: 'verified-portfolio-work',
    title: 'Independent Project Work',
    meta: 'Self-directed - Resume and GitHub verified',
    summary:
      'Built internship-ready full-stack projects across realtime systems, decision-support products, and computer vision, including founding Yor Zenith and supporting the work with public GitHub repositories.',
    bullets: [
      'Built Yor Helios using FastAPI, WebSocket alert streaming, and dashboard workflows for realtime operational monitoring.',
      'Founded Yor Zenith and built a solar planning platform with React and Three.js dashboards for rooftop feasibility and energy generation simulation.',
      'Developed an ML image classifier using OpenCV, LBP/GLCM features, Scikit-Learn SVM, and Streamlit to classify AI-generated versus real photographs.',
      'Maintains public GitHub repositories spanning Next.js web products, Python backend systems, and applied ML/CV projects.',
    ],
    kind: 'verified',
    date: '2026-04-13',
    dateDisplay: 'Resume verified',
  },
  {
    id: 'portfolio-platform',
    title: 'Portfolio Platform',
    meta: 'Personal site - yorayriniwnl.vercel.app',
    summary:
      'Maintains this portfolio as a recruiter-facing product surface with Next.js routing, resume workflows, GitHub-backed data, AI/chat helpers, and interactive sections.',
    bullets: [
      'Architected multi-page routing, shared design tokens, and a consistent editorial system across 18+ active routes.',
      'Integrated public GitHub activity, an AI chat widget, and Three.js experiments while preserving product clarity.',
      'Reconciled stale portfolio claims against live GitHub repositories and resume data for recruiter-facing accuracy.',
    ],
    kind: 'verified',
    date: '2026-01-01',
    dateDisplay: 'Jan 2026 - Present',
  },
]

export const EDUCATION_ITEMS: ExperienceItem[] = [
  {
    id: 'kiit-btech',
    title: 'B.Tech - Computer Science & Communication Engineering',
    meta: 'KIIT Deemed to be University - Expected Graduation: 2027',
    summary:
      'Pursuing B.Tech in Computer Science and Communication Engineering at KIIT Deemed to be University.',
    bullets: [
      'Expected graduation: 2027.',
      'Resume-backed technical focus includes web development, machine learning, computer vision, and SQL fundamentals.',
      'Active in self-directed development work alongside university curriculum.',
    ],
    kind: 'education',
    date: '2023-08-01',
    dateDisplay: '2023 - 2027 expected',
  },
  {
    id: 'kv-burdwan',
    title: 'CBSE - Class XII & X',
    meta: 'Kendriya Vidyalaya, Burdwan',
    summary:
      'Completed secondary and senior secondary education under the Central Board of Secondary Education.',
    bullets: [],
    kind: 'education',
    date: '2022-05-01',
    dateDisplay: 'Completed 2022',
  },
]

export const ACHIEVEMENT_ITEMS: AchievementItem[] = [
  {
    id: 'achievement-zenith',
    title: 'Flagship solar planning project',
    detail:
      'Yor Zenith combines rooftop feasibility analysis, React/Three.js visualization dashboards, and energy generation simulation into one decision-support project.',
    label: 'Verified project',
    kind: 'verified',
    href: '/projects/zenith',
    date: '2026-04-12',
    dateDisplay: 'Apr 2026',
  },
  {
    id: 'achievement-cs2',
    title: 'Top 3% global rank - Counter-Strike 2 Premier',
    detail:
      'Reached the top 3% of the global competitive ladder in Counter-Strike 2 Premier mode.',
    label: 'Competitive Gaming',
    kind: 'verified',
    date: '2024-12-01',
    dateDisplay: 'Dec 2024',
  },
  {
    id: 'achievement-scouts',
    title: 'Bharat Scouts & Guides - Tritiya Sopan',
    detail:
      'Completed Pratham, Dwitiya, and Tritiya Sopan levels in Bharat Scouts & Guides.',
    label: 'Scouts & Leadership',
    kind: 'verified',
    date: '2022-01-01',
    dateDisplay: '2022',
  },
  {
    id: 'achievement-ai-detector',
    title: 'ML image classifier - Yor AI vs Real Image',
    detail:
      'Built a working computer vision pipeline using OpenCV, Scikit-Learn SVM, and texture features (LBP/GLCM) to distinguish synthetic from real photographs.',
    label: 'Verified project',
    kind: 'verified',
    href: '/projects/ai-detector',
    date: '2026-04-12',
    dateDisplay: 'Apr 2026',
  },
]

export const GAME_LIBRARY: GameEntry[] = [
  {
    id: 'strike-arena',
    title: 'Yor Strike Arena',
    subtitle: '3D FPS - Classic tactical feel',
    status: 'Playable now',
    mode: 'playable',
    metric: '1.6-inspired arena',
    detail:
      'A first-person browser shooter with strafing bots, cover-aware skirmishes, manual reloads, and pointer-lock aiming built directly into the site.',
    href: '/games/strike-arena',
  },
  {
    id: 'road-runner',
    title: 'Yor Road Runner',
    subtitle: 'Playable in this site',
    status: 'Playable now',
    mode: 'playable',
    metric: 'Arcade build',
    detail:
      'A browser minigame already present in the project. It stays in the portfolio as the real playable anchor.',
    href: '/games/road-racing',
  },
  {
    id: 'yor-chess',
    title: 'Yor Chess',
    subtitle: 'AI opponent - Strategic gameplay',
    status: 'Playable now',
    mode: 'playable',
    metric: 'Stockfish engine',
    detail:
      'Play chess against a server-routed engine with three difficulty levels, move history, hinting, capture tracking, and session stats.',
    href: '/games/chess',
  },
  {
    id: 'memory-match',
    title: 'Memory Match',
    subtitle: 'Timed puzzle - Tech-stack board',
    status: 'Playable now',
    mode: 'playable',
    metric: 'Easy + hard boards',
    detail:
      'Match portfolio tech-stack cards on easy and hard boards with timed rounds, combo scoring, and keyboard support.',
    href: '/games/memory',
  },
  {
    id: 'snake',
    title: 'Snake',
    subtitle: 'Arcade reflex - Wraparound play',
    status: 'Playable now',
    mode: 'playable',
    metric: '6 food types',
    detail:
      'Classic snake with multiple food behaviors, wall-wrap mode, grid-size selection, and mobile steering.',
    href: '/games/snake',
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic-Tac-Toe',
    subtitle: 'Strategy duel - Minimax AI',
    status: 'Playable now',
    mode: 'playable',
    metric: 'AI difficulty tiers',
    detail:
      'Classic Tic-Tac-Toe with AI difficulty levels, unlockable board expansion, and local session tracking.',
    href: '/games/tic-tac-toe',
  },
  {
    id: 'devwordle',
    title: 'DevWordle',
    subtitle: 'Word game - Daily and free play',
    status: 'Playable now',
    mode: 'playable',
    metric: '5- and 6-letter modes',
    detail:
      'Guess programming terms in daily or free-play modes with code-themed vocabulary and persistent streak tracking.',
    href: '/games/wordle',
  },
  {
    id: 'typing-challenge',
    title: 'Typing Challenge',
    subtitle: 'Code typing - Portfolio snippets',
    status: 'Playable now',
    mode: 'playable',
    metric: 'Real TypeScript snippets',
    detail:
      'Type through real TypeScript snippets from the portfolio codebase and measure pace, accuracy, and stamina.',
    href: '/games/typing',
  },
  {
    id: 'steam-library-placeholder-1',
    title: 'Steam library slot',
    subtitle: 'Public Steam profile not connected',
    status: 'Placeholder',
    mode: 'placeholder',
    metric: 'Hours unavailable',
    detail:
      'Reserved for real playtime and library data once a public Steam profile is connected.',
  },
  {
    id: 'steam-library-placeholder-2',
    title: 'Achievement showcase slot',
    subtitle: 'Awaiting external profile data',
    status: 'Placeholder',
    mode: 'placeholder',
    metric: 'Badges unavailable',
    detail:
      'The interface is ready, but Steam-specific badges and progression are not fabricated here.',
  },
  {
    id: 'project-showcase',
    title: 'Project Showcase Mode',
    subtitle: 'Steam-inspired portfolio shelf',
    status: 'Live',
    mode: 'showcase',
    metric: '9 portfolio projects',
    detail:
      'Transforms verified project cards into a richer profile shelf with progress, stats, and achievement framing.',
    href: '/steam',
  },
]

export const STEAM_PROFILE_PLACEHOLDERS = {
  headline: 'Steam-style profile surface',
  status:
    'Public Steam account data is not connected in this repository, so game hours, badges, and favorite titles remain clearly labeled placeholders.',
  summaryCards: [
    { label: 'Hours played', value: 'Placeholder', note: 'Connect public Steam data' },
    { label: 'Favorite game', value: 'Placeholder', note: 'No Steam profile link found' },
    { label: 'Showcase slot', value: 'Ready', note: 'Uses project cards until external data exists' },
    { label: 'Recent activity', value: 'Portfolio-based', note: 'Using verified site activity instead' },
  ],
}

export const GALLERY_ASSETS: GalleryAsset[] = [
  {
    id: 'hero-shot',
    title: 'Hero Surface',
    src: '/screenshots/hero-screenshot.svg',
    caption: 'A local project asset showing the portfolio hero presentation.',
    tag: 'Portfolio',
  },
  {
    id: 'projects-shot',
    title: 'Project Shelf',
    src: '/screenshots/projects-screenshot.svg',
    caption: 'Project view artwork stored in the repository and reused for gallery framing.',
    tag: 'Projects',
  },
  {
    id: 'zenith-shot',
    title: 'Yor Zenith Case Frame',
    src: '/screenshots/zenith-case-screenshot.svg',
    caption: 'Case-study support artwork for the Yor Zenith project.',
    tag: 'Case Study',
  },
  {
    id: 'og-image',
    title: 'Open Graph Poster',
    src: '/og-image.svg',
    caption: 'Reusable social/brand image already present in the codebase.',
    tag: 'Brand',
  },
]

export const MEDIA_ITEMS: MediaItem[] = [
  {
    id: 'resume-pdf',
    title: 'Resume PDF',
    href: '/resume.pdf',
    summary: 'A downloadable resume generated from my current resume data.',
    kind: 'document',
  },
  {
    id: 'portfolio-demo',
    title: 'Portfolio Demo Archive',
    href: '/demo/index.html',
    summary: 'Standalone HTML demo artifact included in the repository for presentation use.',
    kind: 'demo',
  },
  {
    id: 'delivery-demo',
    title: 'Delivery Practice Demo Archive',
    href: '/delivery/index.html',
    summary: 'Standalone delivery practice demo preserved alongside the main product site.',
    kind: 'demo',
  },
  {
    id: 'brand-poster',
    title: 'Brand Poster',
    href: '/og-image.svg',
    summary: 'Reusable social/brand image already present in the codebase.',
    kind: 'image',
  },
]

export const BLOG_TICKER_ITEMS = [
  'Resume Evidence',
  'GitHub Projects',
  'Solar Planning',
  'Computer Vision',
  'Interface Craft',
  'Learning Systems',
  'Portfolio Architecture',
  'Recruiter Mode',
]

export const BLOG_POSTS: BlogNote[] = [
  {
    category: 'Case Study',
    date: 'Apr 13, 2026',
    excerpt:
      'Refreshing the portfolio meant replacing stretched claims with resume-backed skills, live GitHub repositories, and project descriptions that match the evidence.',
    featured: true,
    readTime: '6 min read',
    title: 'Turning Portfolio Claims into Verified Signals',
    tone: 'real',
  },
  {
    category: 'Project Notes',
    date: 'Apr 12, 2026',
    excerpt:
      'Yor Zenith is strongest when it stays focused on rooftop feasibility, generation forecasting, subsidy logic, and 3D visualization.',
    readTime: '5 min read',
    title: 'What Yor Zenith Proves About Decision-Support Interfaces',
    tone: 'personal',
  },
  {
    category: 'ML Notes',
    date: 'Apr 12, 2026',
    excerpt:
      'The AI detector is a good example of a lightweight classical ML pipeline: OpenCV features, LBP/GLCM texture analysis, SVM training, and Streamlit review.',
    readTime: '4 min read',
    title: 'A Practical Image Classifier Without Inflated Claims',
    tone: 'thoughts',
  },
  {
    category: 'Systems',
    date: 'Apr 11, 2026',
    excerpt:
      'The mentor-mentee system adds Python workflow evidence through Flask, Tkinter, SQLite, and matching logic.',
    readTime: '4 min read',
    title: 'Small Tools Still Need Clear Data Models',
    tone: 'life',
  },
  {
    category: 'Build Log',
    date: 'Apr 10, 2026',
    excerpt:
      'A portfolio works better when missing information stays labeled and real signals stay visible.',
    readTime: '4 min read',
    title: 'Accuracy Is Part of the Interface',
    tone: 'real',
  },
]

export const YOUTUBE_CHANNEL = {
  name: '@YorAyriniwnl',
  href: 'https://www.youtube.com/@YorAyriniwnl',
  videosHref: 'https://www.youtube.com/@YorAyriniwnl/videos',
} as const

export const CS2_VIDEOS: YouTubeVideo[] = [
  {
    id: 'OvQpQW67-PE',
    title: 'Featured CS2 Clip (User requested)',
    duration: '0:46',
    thumbnail: 'https://img.youtube.com/vi/OvQpQW67-PE/mqdefault.jpg',
    note: 'Promoted to lead clip per request',
  },
  {
    id: 'VeN7CFtNtfc',
    title: 'Multiple Plot Twists',
    duration: '2:24',
    thumbnail: 'https://img.youtube.com/vi/VeN7CFtNtfc/mqdefault.jpg',
    note: 'Momentum swings and clutch timing in a single short highlight.',
  },
  {
    id: 'RojL3Y_nnfY',
    title: '5k vs 17k Premier Rating',
    duration: '0:26',
    thumbnail: 'https://img.youtube.com/vi/RojL3Y_nnfY/mqdefault.jpg',
    note: 'High-pressure round against stronger rating opposition.',
  },
  {
    id: 'I_QfzFZkROM',
    title: '4k Anubis',
    duration: '0:42',
    thumbnail: 'https://img.youtube.com/vi/I_QfzFZkROM/mqdefault.jpg',
    note: 'Clean four-kill sequence with confident map control.',
  },
  {
    id: 'fq2vhSnPXiU',
    title: 'Give Me A Flash',
    duration: '0:23',
    thumbnail: 'https://img.youtube.com/vi/fq2vhSnPXiU/mqdefault.jpg',
    note: 'Fast utility timing and conversion under short-round pressure.',
  },
  {
    id: 'KTRUJ6VGdok',
    title: 'No Scope To Suicide',
    duration: '0:13',
    thumbnail: 'https://img.youtube.com/vi/KTRUJ6VGdok/mqdefault.jpg',
    note: 'Quick reaction clip that captures pure CS2 chaos.',
  },
  {
    id: 'PemNc_ugQKw',
    title: 'My Major Ready Team',
    duration: '0:56',
    thumbnail: 'https://img.youtube.com/vi/PemNc_ugQKw/mqdefault.jpg',
    note: 'Team chemistry and comms-focused round sequence.',
  },
]

export const HOME_METRICS = [
  { label: 'Portfolio projects', value: String(PROJECTS.filter((project) => !project.autoGenerated).length).padStart(2, '0') },
  { label: 'Public repos', value: '09' },
  { label: 'Skill signals', value: String(Object.values(SKILL_CATEGORIES).flat().length).padStart(2, '0') },
  { label: 'Graduation', value: '2027' },
]
